language: python
python:
  - "3.6"
install:
  - python setup.py install
  - pip install coveralls pytest-cov
script:
  - pytest --cov-report term-missing --cov=asciigraf tests/
after_success:
  - coveralls
branches:
  only:
    - master
